//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reRack.Design
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        public int korisnik_id { get; set; }
        public int teretana_id { get; set; }
        public int interval_id { get; set; }
        public int id_rezervacija { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual VrInterval VrInterval { get; set; }
        public virtual Teretana Teretana { get; set; }
    }
}
