//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reRack.Design
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teretana
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teretana()
        {
            this.Clanstvo = new HashSet<Clanstvo>();
            this.Recenzija = new HashSet<Recenzija>();
            this.Rezervacija = new HashSet<Rezervacija>();
        }
    
        public int id_teretana { get; set; }
        public int korisnik_id { get; set; }
        public int grad_id { get; set; }
        public string adresa { get; set; }
        public int kapacitet { get; set; }
        public int kvadratura { get; set; }
        public int cijena_clanstva { get; set; }
        public string naziv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clanstvo> Clanstvo { get; set; }
        public virtual Grad Grad { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recenzija> Recenzija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacija { get; set; }

        public override string ToString()
        {
            return naziv;
        }
    }
}
