//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reRack.Design
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zahtjev
    {
        public int id_zahtjev { get; set; }
        public string naziv { get; set; }
        public string adresa { get; set; }
        public int grad_id { get; set; }
        public int kapacitet { get; set; }
        public int kvadratura { get; set; }
        public int cijena_clanstva { get; set; }
        public int korisnik_id { get; set; }
    
        public virtual Grad Grad { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
